on:
  push:
  workflow_dispatch:

jobs:
  deploy:

    strategy:
      fail-fast: false
      matrix:
        number: [0,1,2,3,4,5,6,7,8,9]

    env:
      VERSION: "1.${{ github.run_number }}.${{ matrix.number }}"
      GROUP_ID: com.octokat.app
      ARTIFACT_ID: maven-many-versions
      CLASS_NAME: PublishApp
      SETTINGS_FILE: settings.xml

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Add settings.xml
        run: |
          echo '<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                                http://maven.apache.org/xsd/settings-1.0.0.xsd">
            <activeProfiles>
              <activeProfile>github</activeProfile>
            </activeProfiles>
            <profiles>
              <profile>
                <id>github</id>
                <repositories>
                  <repository>
                    <id>github</id>
                    <url>https://maven.pkg.github.com/${{ github.repository }}</url>
                  </repository>
                </repositories>
              </profile>
            </profiles>
            <servers>
              <server>
                <id>github</id>
                <username>token</username>
                <password>${env.GITHUB_TOKEN}</password>
              </server>
            </servers>
          </settings>' > ${{ env.SETTINGS_FILE }}

      - name: Add simple pom.xml
        run: |
          cat > pom.xml << EOM
          <?xml version="1.0" encoding="UTF-8"?>
          <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
            <modelVersion>4.0.0</modelVersion>
            <groupId>${{ env.GROUP_ID }}</groupId>
            <artifactId>${{ env.ARTIFACT_ID }}</artifactId>
            <version>${{ env.VERSION }}</version>
          </project>
          EOM

      - name: Add ${{ env.CLASS_NAME }}.java file
        run: |
          SOURCE_DIR=src/main/java/$(echo ${{ env.GROUP_ID }} | tr . /)
          mkdir -p $SOURCE_DIR
          SOURCE_PATH=$SOURCE_DIR/${{ env.CLASS_NAME }}.java
          cat <<- END > $SOURCE_PATH
          package ${{ env.GROUP_ID }};
          public class ${{ env.CLASS_NAME }}
          {
              public static void main( String[] args )
              {
                  System.out.println( "Hello from ${{ github.repository }}, commit ${{ github.sha }}, run number ${{ github.run_number }}!" );
              }
          }
          END

      - name: Build package
        run: mvn package --no-transfer-progress

      - name: Run package
        run: java -cp target/${{ env.ARTIFACT_ID }}-${{ env.VERSION }}.jar ${{ env.GROUP_ID }}.${{ env.CLASS_NAME }}

      - name: Deploy package
        run: mvn deploy --settings ${{ env.SETTINGS_FILE }} -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/${{ github.repository }} --no-transfer-progress
        env:
          GITHUB_TOKEN: ${{ github.token }} # GITHUB_TOKEN is the default env for the password

  install:
    runs-on: ubuntu-latest

    env:
      GROUP_ID: com.octokat.app
      ARTIFACT_ID: install-octokat-app
      VERSION: 1.4.0
      CLASS_NAME: InstallApp
      TARGET_GROUP_ID: com.octokat.app
      TARGET_ARTIFACT_ID: maven-many-versions
      TARGET_VERSION: 1.58.7
      TARGET_CLASS_NAME: PublishApp

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Add pom.xml with dependency
        run: |
          cat > pom.xml << EOM
          <?xml version="1.0" encoding="UTF-8"?>
          <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
            <modelVersion>4.0.0</modelVersion>
            <groupId>${{ env.GROUP_ID }}</groupId>
            <artifactId>${{ env.ARTIFACT_ID }}</artifactId>
            <version>${{ env.VERSION }}</version>
            <dependencies>
              <dependency>
                <groupId>${{ env.TARGET_GROUP_ID }}</groupId>
                <artifactId>${{ env.TARGET_ARTIFACT_ID }}</artifactId>
                <version>${{ env.TARGET_VERSION }}</version>
              </dependency>    
            </dependencies>
            <repositories>
              <repository>
                <id>github</id>
                <url>https://maven.pkg.github.com/${{ github.repository_owner }}/*</url>
              </repository>
            </repositories>
          </project>
          EOM
      - name: Add ${{ env.CLASS_NAME }}.java file
        run: |
          SOURCE_PATH=src/main/java/$(echo ${{ env.GROUP_ID }} | tr . /)
          mkdir -p $SOURCE_PATH
          cat <<- END > $SOURCE_PATH/${{ env.CLASS_NAME }}.java
          package ${{ env.GROUP_ID }};
          import ${{ env.TARGET_GROUP_ID }}.${{ env.TARGET_CLASS_NAME }};
          public class ${{ env.CLASS_NAME }}
          {
              public static void main( String[] args )
              {
                  ${{ env.TARGET_CLASS_NAME }}.main( new String[0] );
              }
          }
          END
      - name: Install packages
        run: mvn install --no-transfer-progress
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Exec package
        run: mvn exec:java -D exec.mainClass=${{ env.GROUP_ID }}.${{ env.CLASS_NAME }} --no-transfer-progress
